//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Glossary.Terms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Glossary.Terms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms storage is invalid or inaccessible now. Try to recreate it..
        /// </summary>
        internal static string InvalidTermsStorage {
            get {
                return ResourceManager.GetString("InvalidTermsStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &quot;{0}&quot; is broken or deleted..
        /// </summary>
        internal static string InvalidXmlStorageToLoad {
            get {
                return ResourceManager.GetString("InvalidXmlStorageToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save terms to file &quot;{0}&quot;..
        /// </summary>
        internal static string InvalidXmlStorageToSave {
            get {
                return ResourceManager.GetString("InvalidXmlStorageToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term that is currently edited contains errors..
        /// </summary>
        internal static string TermEditContainsErrors {
            get {
                return ResourceManager.GetString("TermEditContainsErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term name cannot be blank..
        /// </summary>
        internal static string TermEditNameCannotBeBlank {
            get {
                return ResourceManager.GetString("TermEditNameCannotBeBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term &quot;{0}&quot; cannot be added because another term with the same name already exists..
        /// </summary>
        internal static string UnableToAddTermAlreadyExists {
            get {
                return ResourceManager.GetString("UnableToAddTermAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove failed because term &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        internal static string UnableToRemoveNonExistentTerm {
            get {
                return ResourceManager.GetString("UnableToRemoveNonExistentTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed because term &quot;{0}&quot; doesn&apos;t exist..
        /// </summary>
        internal static string UnableToUpdateNonExistentTerm {
            get {
                return ResourceManager.GetString("UnableToUpdateNonExistentTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed because another term with the same name (&quot;{0}&quot;) already exists..
        /// </summary>
        internal static string UnableToUpdateToAnotherExistentTerm {
            get {
                return ResourceManager.GetString("UnableToUpdateToAnotherExistentTerm", resourceCulture);
            }
        }
    }
}
